# ========== Profile ========== #
# avatar
avatar: /avatar/123.jpg
# author name
author: zzl
# signature
signature: witness me
# SNS
social:
  email: 278706081@qq.com
  github: //github.com/zzl2
  weibo: https://weibo.com/u/3807559402?refer_flag=1001030101_
  # zhihu:
  # facebook:
  # twitter:
  # instagram:
  # stack-overflow:
  # linkedin:
  # others:
  # rss: /atom.xml
# friends
friends:
  friendA: //www.baidu.com
  friendB: //www.google.com
  # friendC :
about:
  enable: true
  image: https://zzl2.github.io/2017/12/04/Know-me

# ========== Site ========== #
# title of the site
SEO_title: zzl
# main title
main_title: This my place
# subtitle
subtitle: It's like the wind though the forest
# site haeder image
site_header_image: 'http://oumn0o088.bkt.clouddn.com/intro-desktop.jpg'
# post haeder image
post_header_image: 'http://oumn0o088.bkt.clouddn.com/post-bg.jpg'
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # livere  site: https://livere.com/
  livere_uid: 
  # disqus  site: https://disqus.com/
  disqus_shortname:
  # changyan  site: http://changyan.kuaizhan.com/
  changyan_appid:
  changyan_conf:
  # gitment  site: https://github.com/imsun/gitment
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:
  # youyan  site: http://www.uyan.cc/
  youyan_uid:

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: false
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /assests/favicon.ico
# truncate length (the default is 300)
truncate_length:
# enable toc
toc: true
